apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-dev
  namespace: argocd
  annotations:
    # ArgoCD Image Updater configuration
    argocd-image-updater.argoproj.io/image-list: blog-api=docker.pdlab.dev/blog-api:develop-latest, blog-ui=docker.pdlab.dev/blog-ui:develop-latest, blog-agent=docker.pdlab.dev/blog-agent:latest
    argocd-image-updater.argoproj.io/blog-api.update-strategy: digest
    argocd-image-updater.argoproj.io/blog-ui.update-strategy: digest
    argocd-image-updater.argoproj.io/blog-agent.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default

  source:
    repoURL: https://github.com/PeteDio-Labs/blog-gitops.git
    targetRevision: HEAD
    path: kubernetes/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: blog-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 10
