apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - prometheus-rules.yaml
  - mc-plan-alerts.yaml
  - mc-plan-alertmanager-config.yaml
  - mc-webhook-am-token-sealedsecret.yaml
  - grafana-ingress.yaml
  - network-policies.yaml

labels:
  - pairs:
      layer: platform
