---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mc-webhook-am-token
  namespace: observability
spec:
  encryptedData:
    token: AgBRL8PRvs+DSAZhN7o0yVKulEOjNVDTJzuB7JbfszKCCUlVId3rLEmDEKgLpBsSz+xwPp4kIWly22c73onkwVDY+I5pcLHZ6GG+YnZY40675bB1NCsfOk30xfSqaHI2dwKYujNFk6IUHQ5TLbs+OaXIrHobLQS6plm5OT/qmYWqYFyuU9dc1ueIzKr82790M6++gCHg59mcKxR6KOaGJ80wqgFPr52sRwZjf8qUoxKdtEvMwvpnPLxbaXQBkYAkjBXbmE3cxZBXIxCUaz1JludhQHEGpxcosvyQOttsdwOL8o2FIv1bAjNVODnb0uoQX+Nl1Zhu+t9cjoEQmk5xy2lzf5gqD0bBPc96p1VTLANIPcVD88anfYlNmMw1UF04yRdzGsAi4kuGAwjxQtc3LddwL/WZ/hlH709r7aK1SANxuK0fX81Zf99S4zpfsK4mIJySA5Y1JtI4mt/5mIS6O+Nx5R3tiaLphmoM/yqY5S/AxqOfkPZG68kU6gV9eQ4xA54OO8aJkMk0Iho+p6wzeRu+sAVEJU38CA4qkjdTUkOb+QPg01ZgAzAfMOetcVamXeu8EYN+lqiS5COmXrukJ1aMvhTOecT0vbx3DNs859PX0CERyVqCfBSkvlYovKEyCvPmP19ezDoeqZCzt9+u2lOkTBR0Aw3PezOewbFScCiNVaLfAyFJxbLSwKlVCXF9NfqT5utMWVw99SU0QXL5E1WH9Vg2ZrOR00vPElcmdfkPvK6ipoox7ESd4rvTT95JADjhdTtvhbRZj0cj4Tpp87xA
  template:
    metadata:
      name: mc-webhook-am-token
      namespace: observability
